apiVersion: v1
kind: Service
metadata:
  name: taxpayer-api
  namespace: domain-api-taxpayer
spec:
  selector:
    app: taxpayer-api
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
