apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  namespace: domain-api-payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-api
  template:
    metadata:
      labels:
        app: payment-api
    spec:
      containers:
        - name: prism
          image: stoplight/prism:latest
          args:
            - mock
            - -h
            - "0.0.0.0"
            - -p
            - "80"
            - /specs/payment-api.yaml
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: specs
              mountPath: /specs
              readOnly: true
            - name: shared
              mountPath: /shared
              readOnly: true
          livenessProbe:
            httpGet:
              path: /payments
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /payments
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: specs
          configMap:
            name: payment-api-spec
            items:
              - key: payment-api.yaml
                path: payment-api.yaml
        - name: shared
          configMap:
            name: payment-api-spec
            items:
              - key: shared-components.yaml
                path: shared-components.yaml
