apiVersion: v1
kind: Service
metadata:
  name: income-tax-api
  namespace: domain-api-income-tax
spec:
  selector:
    app: income-tax-api
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
