apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  namespace: domain-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      imagePullSecrets:
        - name: gh-docker-registry-creds
      containers:
        - name: static-server
          image: ghcr.io/craigedmunds/domain-api-docs:latest
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: GATEWAY_HOST
              value: "domain-api.lab.local.ctoaas.co"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
