apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: domain-api-gateway
  namespace: domain-api
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`domain-api.lab.local.ctoaas.co`)
      kind: Rule
      services:
        - name: gateway
          port: 80
  tls:
    certResolver: letsencrypt
